# Copyright (c) 2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

env_name: black_items_in_bin
external_yaml: ../scenes/workdesk_bin.yaml
task:
  composition: parallel
  description: Put the black items in the grey bin
  subtasks:
  - kind: PickAndPlaceTask
    params:
      pick_up_object: keyboard
      destination_location: grey_bin
      background_scene: maple_table_robolab
      episode_length_s: 70.0
  - kind: PickAndPlaceTask
    params:
      pick_up_object: remote_control
      destination_location: grey_bin
      background_scene: maple_table_robolab
      episode_length_s: 70.0
  - kind: PickAndPlaceTask
    params:
      pick_up_object: computer_mouse
      destination_location: grey_bin
      background_scene: maple_table_robolab
      episode_length_s: 70.0
  - kind: PickAndPlaceTask
    params:
      pick_up_object: smartphone
      destination_location: grey_bin
      background_scene: maple_table_robolab
      episode_length_s: 70.0
  - kind: PickAndPlaceTask
    params:
      pick_up_object: glasses
      destination_location: grey_bin
      background_scene: maple_table_robolab
      episode_length_s: 70.0
