# Copyright (c) 2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

env_name: clutter_pumpkin
external_yaml: ../scenes/clutter_fruit_bottle_bluebin.yaml
task:
  composition: parallel
  description: Put all the pumpkins away in the bin
  subtasks:
  - kind: PickAndPlaceTask
    params:
      pick_up_object: pumpkin_large
      destination_location: container_f24
      background_scene: maple_table_robolab
      episode_length_s: 70.0
  - kind: PickAndPlaceTask
    params:
      pick_up_object: pumpkin_small
      destination_location: container_f24
      background_scene: maple_table_robolab
      episode_length_s: 70.0
