# Copyright (c) 2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

env_name: larger_object_raisin_box_in_bin
external_yaml: ../scenes/butter_raisin_box_grey_bin.yaml
task:
  composition: atomic
  description: Pick up the red raisin box and place it into the grey bin on the maple table.
  subtasks:
  - kind: PickAndPlaceTask
    params:
      pick_up_object: raisin_box
      destination_location: grey_bin
      background_scene: maple_table_robolab
      episode_length_s: 70.0
