# Copyright (c) 2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

"""Prepare, verify and synchronize the versioned USDCraft-Scene asset repository."""

import argparse
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path
from tempfile import TemporaryDirectory

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from isaaclab_arena.assets.usdcraft_scene import bundle_root  # noqa: E402

LOCK = Path(__file__).with_name("release.json")
REPO = "xingyoujun/USDCraft-Scene"


def digest(path):
    """Return a file's SHA-256 digest."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_json(path, value):
    """Write deterministic UTF-8 JSON."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n")


def inside(root, relative):
    """Resolve a manifest-relative path without escaping its bundle."""
    path = root / relative
    assert not Path(relative).is_absolute() and path.resolve().is_relative_to(root.resolve()), relative
    return path


def verify(root):
    """Validate all manifest files and entrypoints without starting Isaac Sim."""
    manifest = json.loads((root / "manifest.json").read_text())
    assert manifest["schema_version"] == 1
    for name, record in manifest["files"].items():
        path = inside(root, name)
        assert path.is_file(), f"Missing file: {name}"
        assert path.stat().st_size == record["bytes"] and digest(path) == record["sha256"], f"Changed file: {name}"
    for record in manifest["entries"].values():
        assert record["path"] in manifest["files"], record
    print(f"Verified {len(manifest['files'])} files, {sum(r['bytes'] for r in manifest['files'].values())} bytes")
    return manifest


def prepare(args):
    """Package source payloads once with stable IDs and preserved internal USD references."""
    out = args.directory
    assert not out.exists(), f"Refusing to overwrite a release directory: {out}"
    out.mkdir(parents=True)
    entries = {}
    robot = out / "embodiments/pine_wm/robot"
    shutil.copytree(args.scene_source / "assets/ur7e_gripper", robot)
    entries["pine_wm_ur7e"] = {"path": "embodiments/pine_wm/robot/ur7e_gripper.usd", "kind": "embodiment"}
    calibration = ROOT / "isaaclab_arena/embodiments/ur7e/calibration/pine_wm"
    shutil.copytree(calibration, out / "embodiments/pine_wm/calibration")
    source_tasks = json.loads((args.objects_source / "configs/tasks.json").read_text())["tasks"]
    bindings = {key: value for task in source_tasks for key, value in task["asset_bindings"].items()}
    for key, value in sorted(bindings.items()):
        name = key.removeprefix("P20_")
        if name.startswith("cube_"):
            name += "mm"
        if name == "drawer":
            name = "drawer_first20"
        source = args.objects_source / value["entry"]
        target = out / "assets" / name
        shutil.copytree(source.parent, target)
        entries[key] = {
            "path": (target / source.name).relative_to(out).as_posix(),
            "kind": "object",
            "source_record_id": value["record_id"],
            "source_sha256": digest(source),
        }
    # Runtime task semantics remain owned by Git; HF records the exact release bindings.
    task_ids = {task["task_id"]: list(task["asset_bindings"]) for task in source_tasks}
    write_json(
        out / "scenes/pine_wm/scene.json",
        {
            "schema_version": 1,
            "environment": "pine_wm",
            "embodiment": "pine_wm_ur7e",
            "implementation": "isaaclab_arena_environments/pine_wm_environment.py",
            "geometry": "Procedural slotted aluminium table and lights, generated by Arena code; no baked scene USD.",
            "table_top_z_m": 0.74,
            "robot_position_m": [0.0, -0.425, 0.75],
            "cameras": ["realsense_d435", "wrist_a", "wrist_b", "scene_cam"],
            "task_assets": task_ids,
        },
    )
    entries["pine_wm"] = {"path": "scenes/pine_wm/scene.json", "kind": "scene"}
    shutil.copy2(ROOT / "data_engine/pine_wm/review_layouts.json", out / "scenes/pine_wm/review_layouts.json")
    (out / "README.md").write_text(
        "---\npretty_name: USDCraft-Scene\ntask_categories:\n- robotics\n---\n\n"
        "# USDCraft-Scene\n\nVersioned simulation assets for Arena.\n\n"
        "- `embodiments/pine_wm/`: UR7e/Robotiq payload and camera calibration.\n"
        "- `scenes/pine_wm/`: procedural scene descriptor and reviewed layout parameters.\n"
        "- `assets/`: shared task objects, independent of any scene or embodiment.\n"
        "- `manifest.json`: stable IDs, relative entrypoints, checksums and source provenance.\n\n"
        "Preserve USD subdirectories and references when downloading. Robot materials require Isaac Sim's "
        "OmniPBR.mdl runtime shader. Table, camera housings and printed brackets are generated by Arena code; "
        "this bundle is not a standalone simulator or a baked full scene.\n\n"
        "No videos, datasets, checkpoints, credentials, original archives or backup copies are included. "
        "Robot sources are collected Isaac assets; object provenance is retained in the manifest. "
        "This private bundle does not assign a new license to upstream assets.\n"
    )
    (out / ".gitattributes").write_text(
        "*.usd filter=lfs diff=lfs merge=lfs -text\n*.usdc filter=lfs diff=lfs merge=lfs -text\n"
        "*.usda filter=lfs diff=lfs merge=lfs -text\n*.png filter=lfs diff=lfs merge=lfs -text\n"
    )
    files = {}
    for path in sorted(out.rglob("*")):
        if path.is_file():
            files[path.relative_to(out).as_posix()] = {"sha256": digest(path), "bytes": path.stat().st_size}
    write_json(
        out / "manifest.json",
        {
            "schema_version": 1,
            "repository": REPO,
            "repo_type": "dataset",
            "entries": entries,
            "runtime_dependencies": ["Isaac Sim (OmniPBR.mdl)", "Isaac Lab", "IsaacLab-Arena Pine WM code"],
            "sources": [args.scene_source.name, args.objects_source.name],
            "files": files,
        },
    )
    verify(out)


def audit_usd(args):
    """Check relocated USD dependency closure, allowing only the Isaac runtime shader."""
    from pxr import UsdUtils

    manifest = verify(args.directory)
    checked = set()
    for entry in manifest["entries"].values():
        path = args.directory / entry["path"]
        if path.suffix not in {".usd", ".usda", ".usdc"}:
            continue
        layers, assets, unresolved = UsdUtils.ComputeAllDependencies(str(path))
        assert set(unresolved) <= {"OmniPBR.mdl"}, (path, unresolved)
        dependencies = [Path(layer.realPath) for layer in layers if layer.realPath] + [Path(p) for p in assets]
        for dependency in dependencies:
            dependency = dependency.resolve()
            assert dependency.is_relative_to(args.directory.resolve()), dependency
            assert dependency.relative_to(args.directory.resolve()).as_posix() in manifest["files"], dependency
        checked.add(entry["path"])
    print(f"USD closure verified for {len(checked)} entrypoints; only OmniPBR.mdl requires Isaac Sim")


def upload(args):
    """Publish a verified release privately and pin the returned HF commit in Git-side metadata."""
    from huggingface_hub import HfApi, snapshot_download

    manifest = verify(args.directory)
    assert not manifest.get("local_extension"), "Stage a complete release candidate before publishing G2"
    plan_path = getattr(args, "release_plan", None)
    plan = json.loads(plan_path.read_text()) if plan_path else None
    if "g2" in manifest["entries"]:
        assert plan is not None, "G2 publication requires a reviewed --release-plan"
    if plan:
        assert plan["repo_id"] == REPO and plan["repo_type"] == "dataset"
        assert plan["manifest_sha256"] == digest(args.directory / "manifest.json"), "Candidate changed"
    api = HfApi()
    if plan is None:
        api.create_repo(REPO, repo_type="dataset", private=True, exist_ok=True)
    info = api.repo_info(REPO, repo_type="dataset")
    assert info.private, "Existing repository is public; refusing this private upload"
    if plan:
        assert info.sha == plan["expected_parent_revision"], "Remote advanced; merge its new manifest and restage"

    # Never remove other scenes or embodiments from the shared repository.
    remote_files = api.list_repo_files(REPO, repo_type="dataset")
    assert all(
        name in manifest["files"] or name == "manifest.json" for name in remote_files
    ), "Repository contains another release: merge its manifest before publishing; do not overwrite it."
    result = api.upload_folder(
        repo_id=REPO,
        repo_type="dataset",
        folder_path=args.directory,
        allow_patterns=[*manifest["files"], "manifest.json"],
        commit_message="Update versioned Arena embodiments, scenes and shared assets",
        parent_commit=info.sha,
    )
    # HF may add LFS rules to .gitattributes. Do not pin a release whose remote
    # payload differs from its manifest, even when the upload request succeeded.
    with TemporaryDirectory(prefix="arena_hf_verify_") as directory:
        snapshot_download(
            repo_id=REPO,
            repo_type="dataset",
            revision=result.oid,
            local_dir=directory,
            allow_patterns=[*manifest["files"], "manifest.json"],
        )
        downloaded = Path(directory)
        assert digest(downloaded / "manifest.json") == digest(args.directory / "manifest.json"), result.oid
        verify(downloaded)
    write_json(
        LOCK,
        {
            "repo_id": REPO,
            "repo_type": "dataset",
            "revision": result.oid,
            "manifest_sha256": digest(args.directory / "manifest.json"),
        },
    )
    print(f"Published https://huggingface.co/datasets/{REPO}/tree/{result.oid}")


def download(args):
    """Download only the pinned release files and verify their hashes."""
    from huggingface_hub import hf_hub_download, snapshot_download

    lock = json.loads(LOCK.read_text())
    assert re.fullmatch(r"[0-9a-f]{40}", lock["revision"]), "A published immutable revision is required"
    existing = args.directory / "manifest.json"
    if existing.exists():
        assert (
            digest(existing) == lock["manifest_sha256"]
        ), "Destination contains a different or locally extended release; download into a new directory"
    args.directory.mkdir(parents=True, exist_ok=True)
    manifest_path = Path(
        hf_hub_download(
            lock["repo_id"],
            "manifest.json",
            repo_type="dataset",
            revision=lock["revision"],
            local_dir=args.directory,
        )
    )
    assert digest(manifest_path) == lock["manifest_sha256"], "Unexpected release manifest"
    manifest = json.loads(manifest_path.read_text())
    for name in manifest["files"]:
        inside(args.directory, name)
    snapshot_download(
        lock["repo_id"],
        repo_type="dataset",
        revision=lock["revision"],
        local_dir=args.directory,
        allow_patterns=[*manifest["files"], "manifest.json"],
    )
    verify(args.directory)
    print(f"Set ARENA_USDCRAFT_SCENE_ROOT={args.directory.resolve()}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    for name in ("prepare", "verify", "audit-usd", "upload", "download"):
        command = commands.add_parser(name)
        command.add_argument("directory", type=Path, nargs="?", default=bundle_root())
        if name == "upload":
            command.add_argument("--release-plan", type=Path)
        if name == "prepare":
            command.add_argument("--scene-source", type=Path, required=True)
            command.add_argument("--objects-source", type=Path, required=True)
    args = parser.parse_args()
    if args.command == "verify":
        verify(args.directory)
    else:
        {"prepare": prepare, "audit-usd": audit_usd, "upload": upload, "download": download}[args.command](args)


if __name__ == "__main__":
    main()
